# Generated by Django 5.2 on 2025-04-22 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 14, 37, 15, 810340, tzinfo=datetime.timezone.utc), help_text='The creation date of the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(db_comment='The URI encoded post title', help_text='The URI encoded post title', max_length=60, unique=True),
        ),
    ]
