# Generated by Django 5.2 on 2025-04-22 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(db_comment='The creation date of the post', default=datetime.datetime(2025, 4, 22, 15, 12, 31, 150153, tzinfo=datetime.timezone.utc), help_text='The creation date of the post'),
        ),
    ]
