# Generated by Django 5.2 on 2025-04-20 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='The URI encoded post title', max_length=60, unique=True)),
                ('title', models.CharField(help_text='The post title, describing the global topic', max_length=60)),
                ('content', models.TextField(help_text='The post body/content, containing rich text for Markdown display')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 4, 20, 13, 57, 29, 131868, tzinfo=datetime.timezone.utc), help_text='The creation date of the post')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The most recent update date of the post', null=True)),
            ],
        ),
    ]
