# Generated by Django 5.2 on 2025-04-22 14:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_at_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(db_comment='The post body/content, containing rich text for Markdown display', help_text='The post body/content, containing rich text for Markdown display'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(db_comment='The creation date of the post', default=datetime.datetime(2025, 4, 22, 14, 38, 7, 937106, tzinfo=datetime.timezone.utc), help_text='The creation date of the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_comment='The post title, describing the global topic', help_text='The post title, describing the global topic', max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='The most recent update date of the post', help_text='The most recent update date of the post', null=True),
        ),
    ]
