# Generated by Django 5.2 on 2025-04-22 16:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(db_comment='The creation date of the post', default=datetime.datetime(2025, 4, 22, 16, 8, 25, 282022, tzinfo=datetime.timezone.utc), help_text='The creation date of the post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_comment='The most recent update date of the post', help_text='The most recent update date of the post', null=True),
        ),
    ]
