# Generated by Django 5.2 on 2025-05-24 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_comment='The post body/content, containing rich text for Markdown display', help_text='The post body/content, containing rich text for Markdown display')),
                ('created_at', models.DateTimeField(db_comment='The creation date of the thumbnail object', default=django.utils.timezone.now, help_text='The creation date of the thumbnail object')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postthumbnail'),
        ),
    ]
