# Generated by Django 5.2 on 2025-05-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_postthumbnail_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postthumbnail'),
        ),
        migrations.AlterField(
            model_name='postthumbnail',
            name='url',
            field=models.URLField(db_comment='The thumbnail media URL', help_text='The thumbnail media URL'),
        ),
    ]
