# Generated by Django 5.2 on 2025-05-24 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_thumbnail_alter_postthumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('JAPAN', 'Japan'), ('AUTOMOTIVE', 'Automotive')], db_comment='The category name', help_text='The category name', max_length=25, unique=True)),
                ('created_at', models.DateTimeField(db_comment='The creation date of the category object', default=django.utils.timezone.now, help_text='The creation date of the category object')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, db_comment='The URI encoded post title', help_text='The URI encoded post title', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.postthumbnail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='blog.postcategory'),
        ),
    ]
